# Generated by Django 4.2.3 on 2023-08-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(default='image', upload_to='pics'),
            preserve_default=False,
        ),
    ]
